# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoilerFlex' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoilerFlex
  pod "Firebase/Core"
  pod "Firebase/Firestore"

  target 'BoilerFlexTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoilerFlexUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
